### ISSUE TITLE
Crash with invalid credentials

### ISSUE THREAD

**Issue by SchrodingersGat** [clj/kom2#13]
I have discovered one source of crash: 

If your `.kicad_dbl` configuration file has invalid InvenTree credentials, KiCad simply crashes without warning.

This is repeatable, and there is no "error message" or anything, simply a hard crash out of the KiCad application

**Comment by clj** [comment]
Thanks for your testing!

I am in the process of removing panics (i.e. the driver just quits) which should generally help with crashes. This doesn't seem to be directly related to that since connecting is one of the places where I'm fairly sure that failing to get API credentials will return an error to the driver manager instead of panicking. I'll investigate.

**Comment by SchrodingersGat** [comment]
Running on windows (kicad v7.0.6) this is very consistent. The following connection strings work ok:

- `"connection_string": "Driver=kom2;username=admin;password=inventree;server=http://localhost:8000/"`
- `"connection_string": "Driver=kom2;usernamE=admin;pAsSWord=inventree;server=http://localhost:8000/",`

The following ones fail:

- `"connection_string": "Driver=kom2;username=admin;password=inventree;server=http://localhost:8000/wrong-endpoint",`
- `"connection_string": "Driver=kom2;username=admin;password=inventree;servexr=http://localhost:8000/",`
- `"connection_string": "Driver=kom2;username=admin;passwork=inventree;server=http://localhost:8000/",`
- `"connection_string": "Driver=kom2;usernamer=admin;password=inventree;server=http://localhost:8000/"`
- `"connection_string": "Driver=kom2;username=admin;password=inventree;server=https://localhost:8000/",`

Failures are completely without any error message. I'm wondering if this might be on the KiCad side, might be worth raising a bug report. Can you think of any debugging I could do locally?

**Comment by clj** [comment]
One thing you could try is  to enable the ODBC trace log for these cases and post those. It might give an insight into why things are crashing. I'll see if I can find time to try on my Windows VM tonight.

I think the likelihood of this being a problem in KiCad is slim, it is using an ODBC library to abstract some of that complexity away and I'd at least want to do a bit more investigation of this on my side before I log anything with KiCad.

I did have a debug build of KiCad, but it took 40GB of disk space on my VM and I had to delete it as I ran out of disk. :/ I'll try to provision a new VM with more disk next time!

**Comment by clj** [comment]
So I think I have made some progress. The Driver Manager was stealth calling a different function (SQLGetDiagField instead of SQLGetDiagRec, which is what the ODBC library was calling) to get the error information. I have now gotten the tests to pass on Windows and I have tested a few of your connection strings above, and I don't get a crash, but an error message:

<img width="816" alt="image" src="https://github.com/clj/kom2/assets/26661/5a476381-9ec2-4270-a272-428b460d81f2">

I haven't made a release yet, I'll do that tomorrow.

**Comment by SchrodingersGat** [comment]
This looks like a great advance! LMK when there's a release and I'll check it out.

**Comment by clj** [comment]
I have pushed a new release which should fix this particular bug, but hopefully also lots of the others you have seen. I haven't had time to go through and test them all though. 

The release removes all explicit `panics` from the code so took a bit longer than I'd thought to get out the door (I also added tests 🤯 ). Hitting any of those panics would have caused KiCad to crash. I also fixed some other errors that would have caused crashes. So fingers crossed this will provide a better user experience.

**Comment by SchrodingersGat** [comment]
@clj just tried the latest installer and unfortunately still get a hard crash if the credentials are wrong on Windows

**Comment by clj** [comment]
Are you able to verify that the latest DLL is actually installed and used? Not sure how best to do that though :) and I’m currently not able to get to a windows machine until the weekend.

**Comment by SchrodingersGat** [comment]
@clj I have just done a complete clean of any old drivers, including clearing out the registry, and then a fresh install.

I still get a hard crash when the wrong credentials are used.

**Comment by clj** [comment]
@SchrodingersGat that is really annoying :) could you let me know what Windows version you are using? I'm wondering if your version of Windows is different than mine and perhaps the driver manager works differently...

**Comment by SchrodingersGat** [comment]
I've tried this on two computers now both running windows 10

**Comment by clj** [comment]
@SchrodingersGat I have provisioned a Windows 10 VM for testing and noticed that (on Windows 10, but not 11) even though the function to get error information says that there is no data, any passed buffers must have nulls written to them, since something still tries to look at them.

I have also fixed things so that the driver also now works for KiCad 7.0.7.

There is a new release up.

**Comment by SchrodingersGat** [comment]
@clj I've checked the new release and unfortunately I still get the hard crash every time I run with invalid credentials.

Have you checked with invalid credentials (i.e. bad username / password) on your end?

**Comment by clj** [comment]
@clj Thanks for checking again and sorry this still isn't working. This works for me on Windows 10:

I have set up .kicad_dbl file with invalid credentials:
<img width="793" alt="Screenshot 2023-09-05 at 07 40 55" src="https://github.com/clj/kom2/assets/26661/09ad16a3-0184-4b01-8c6e-198159794f74">

Running the following versions: KiCad 7.0.7, Windows 10, Kom2 20230904
<img width="957" alt="Screenshot 2023-09-05 at 07 37 29" src="https://github.com/clj/kom2/assets/26661/65de4f7c-ec9d-44cd-8a9f-baeabbdbdff5">

And I definitely get an error message and not a crash:
<img width="868" alt="Screenshot 2023-09-05 at 07 35 02" src="https://github.com/clj/kom2/assets/26661/5dd8a93a-c7d7-420f-a20b-a7c122c48e72">


I'm not sure what could be different between our versions (other than the KiCad version, I'll try that shortly, but I doubt it that will make a difference).

Are you using a username and password? or username and api key directly?
